name: "Clean Up Dns Resources"

on:
  schedule:
    # triggers the workflow every day at 7:15 and 8:15 UTC = 1:15 and 2:15 CST
    - cron: "15 7,8 * * *"
  workflow_dispatch:
    inputs:
      resourceTypes:
        description: "Resource Types"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - dns

jobs:
  clean_up_resource:
    name: "Clean Up Dns Resource"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Delete DNS
        run: doctl compute domain list | awk '{print $1}' | awk 'NR!=1 {print}' | xargs doctl compute domain delete -f
