on:
  push:
    branches:
      - main

jobs:
  deploy:
    run-on: ubuntu-latest

    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}